### PR TITLE
Update license & dependencies to latest stable versions

### PR DESCRIPTION
**Pull request by hackertronix**
Noticed a lot of the files still reference RayWenderlich instead of Kodeco, so I updated the references.

The dependencies in this project are also very out of date so I updates those here as well

### CODE REVIEW

**Comment by VegetarianZombie** [comment]
HI @hackertronix, thanks so much for putting this together. I've gone over the project and the updates are great. Since the time that you submitted to the time I just reviewed, Android Studio Hedgehog was released. Would you be able to update the project dependencies to work on Hedgehog without any issue?

**Comment by hackertronix** [comment]
> HI @hackertronix, thanks so much for putting this together. I've gone over the project and the updates are great. Since the time that you submitted to the time I just reviewed, Android Studio Hedgehog was released. Would you be able to update the project dependencies to work on Hedgehog without any issue?

Just saw this now @VegetarianZombie ... Sorted out the AGP & gradle versions for HedgeHog... This should work without any hiccups now 🫡

**Comment by hackertronix** [comment]
@VegetarianZombie I have rebased this PR with `master` let me know if this is good to go. 😇

**Comment by VegetarianZombie** [comment]
@hackertronix  Looks great! Thank you for fixing those issues.

**Pull request merged**
